"""Tasks the system has never been shown, for measuring what it does unaided.

Arm D scored 51/100 on the same hundred tasks the recordings were made from.
Different member numbers, but the same set — so that number answers "can it
repeat itself", not "can it handle work it has not seen". This set answers the
second question, and separates the three ways a task can be new:

    H1  a recorded shape, with arguments it has never run. `Look up member
        40021 and report the checking balance` was recorded only for member
        40055. If a recording is a capability rather than a replay of one
        afternoon, this is where it shows.

    H2  a shape never recorded at all, reading labelled fields the survey
        mapped. The cache holds nothing for these by construction, so they
        measure the map alone: whether surveying an application is enough to do
        something nobody demonstrated.

    H3  rows, counts, selection and refusals — the answers that are not a field.

Everything here is generated by enumerating the application's own data rather
than chosen, so the set cannot be quietly stacked with the tasks likely to pass.
Three rules keep a generated task from being impossible rather than hard, each
of them learned by writing a task that was:

  * **Nothing is asked of the restricted member except the refusal.** Every
    other screen for that member — contact, orders, audit — is reached *through*
    the member record, and the record refuses. An earlier draft asked for that
    member's telephone number and audit count; both were unanswerable through
    the UI the application actually offers.

  * **No row is asked for that does not exist.** A member with no posted items
    has no third one, and a task whose answer is absent measures nothing.

  * **Every expected answer comes from the fixtures, and tools/check_holdout.py
    confirms it is on the screen the task must reach.** A wrong expectation
    looks exactly like a hard task.

That none of this overlaps tools/tasks100.py is asserted at import.
"""

from __future__ import annotations

from bench import Task
from tasks100 import AUDIT, CONTACT, HISTORY, MEMBERS, ORDERS, STATEMENTS, WORK
from tasks100 import TASKS as TRAINED

OPEN = [m for m, d in MEMBERS.items() if not d["restricted"]]        # 40021 40055 40204
RESTRICTED = [m for m, d in MEMBERS.items() if d["restricted"]][0]   # 40113
ABSENT = ["40777", "40999", "41010"]                                 # not on file

TASKS: list[Task] = []
_n = 0

_trained_runs = {(t.goal, tuple(sorted(t.params.items()))) for t in TRAINED}
_trained_shapes = {t.goal for t in TRAINED}


SKIPPED: list[tuple[str, dict]] = []


def add(goal, outputs, params=None, hazards=None, patterns=None,
        mutates=False, group="H1", note="") -> None:
    """Add a task, unless the trained set already ran exactly it.

    Enumeration walks into the trained set from time to time — the second posted
    item of member 40021 is asked there and would be generated here. Skipping is
    the whole point of the set, so it happens quietly and is counted.
    """
    global _n
    if (goal, tuple(sorted((params or {}).items()))) in _trained_runs:
        SKIPPED.append((goal, params or {}))
        return
    _n += 1
    TASKS.append(Task(_n, goal, outputs, params or {}, hazards or {}, patterns or {},
                      mutates, note=f"[{group}] {note}".strip()))


def tier(task: Task) -> str:
    return task.note.split("]")[0].lstrip("[") if task.note.startswith("[") else "?"


def _work(item_id: str) -> dict:
    return next(w for w in WORK if w["id"] == item_id)


# What each output name means in the application's own data. An output that is
# not here cannot have a task generated for it, because only these can be
# answered from the fixtures without a person deciding what the answer is.
FIELD = {
    "savings": lambda m, p=None: MEMBERS[m]["savings"],
    "checking": lambda m, p=None: MEMBERS[m]["checking"],
    "status": lambda m, p=None: MEMBERS[m]["status"],
    "branch": lambda m, p=None: MEMBERS[m]["branch"],
    "member_name": lambda m, p=None: MEMBERS[m]["name"],
    "phone": lambda m, p=None: CONTACT[m]["phone"],
    "email": lambda m, p=None: CONTACT[m]["email"],
    "postcode": lambda m, p=None: CONTACT[m]["postcode"],
    "post_code": lambda m, p=None: CONTACT[m]["postcode"],
    "opening": lambda m, p: STATEMENTS[(m, p)]["opening"],
    "credits": lambda m, p: STATEMENTS[(m, p)]["credits"],
    "debits": lambda m, p: STATEMENTS[(m, p)]["debits"],
    "closing": lambda m, p: STATEMENTS[(m, p)]["closing"],
    "items": lambda m, p: STATEMENTS[(m, p)]["items"],
}


# ============================================ H1  a recorded shape, new arguments ==

for _shape in sorted(_trained_shapes):
    _like = [t for t in TRAINED if t.goal == _shape]
    _outputs = list(_like[0].outputs)
    if not all(o in FIELD for o in _outputs):
        continue
    _params = set(_like[0].params)
    if _params == {"member_no"}:
        _candidates = [{"member_no": m} for m in OPEN]
    elif _params == {"member_no", "period"}:
        _candidates = [{"member_no": m, "period": p} for m, p in sorted(STATEMENTS)]
    else:
        continue
    for _args in _candidates:
        if (_shape, tuple(sorted(_args.items()))) in _trained_runs:
            continue
        add(_shape,
            {o: FIELD[o](_args["member_no"], _args.get("period")) for o in _outputs},
            dict(_args), note="an argument the trained set never ran")


# ================================================== H2  a shape never recorded ==
# Enumerated over the fields the survey mapped: every single read nobody asked
# for, then every adjacent pair on the same screen.

_RECORD = [("the member's name", "member_name"), ("the account status", "status"),
           ("the branch holding the record", "branch"),
           ("the savings balance", "savings"), ("the checking balance", "checking")]
_CONTACT = [("the telephone number", "phone"), ("the e-mail address", "email"),
            ("the post code", "post_code")]
_STATEMENT = [("the opening balance", "opening"), ("the total credits", "credits"),
              ("the total debits", "debits"), ("the closing balance", "closing"),
              ("the number of items", "items")]

for _member in OPEN:
    for _phrase, _name in _RECORD:
        goal = "Look up member {member_no} and report " + _phrase
        if goal in _trained_shapes:
            continue
        add(goal, {_name: FIELD[_name](_member)}, {"member_no": _member}, group="H2",
            note="one mapped field, never asked for")

# Pairs off one screen: two reads, one route, and neither pair was recorded.
for _member in OPEN:
    for (_pa, _na), (_pb, _nb) in ((_RECORD[1], _RECORD[2]), (_RECORD[3], _RECORD[4]),
                                   (_RECORD[0], _RECORD[2])):
        add(f"Look up member {{member_no}} and report {_pa} and {_pb}",
            {_na: FIELD[_na](_member), _nb: FIELD[_nb](_member)},
            {"member_no": _member}, group="H2", note="two fields off one mapped screen")

for _member in OPEN:
    for (_pa, _na), (_pb, _nb) in ((_CONTACT[0], _CONTACT[1]), (_CONTACT[1], _CONTACT[2]),
                                   (_CONTACT[0], _CONTACT[2])):
        add(f"Report {_pa} and {_pb} on file for member {{member_no}}",
            {_na: FIELD[_na](_member), _nb: FIELD[_nb](_member)},
            {"member_no": _member}, group="H2", note="two fields off the contact screen")

for _member, _period in sorted(STATEMENTS):
    for (_pa, _na), (_pb, _nb) in ((_STATEMENT[0], _STATEMENT[3]),
                                   (_STATEMENT[1], _STATEMENT[2])):
        add(f"Produce the {{period}} statement for member {{member_no}} and report "
            f"{_pa} and {_pb}",
            {_na: FIELD[_na](_member, _period), _nb: FIELD[_nb](_member, _period)},
            {"member_no": _member, "period": _period}, group="H2",
            note="two statement fields, each recorded alone")

add("Report the member number shown on the contact details screen for member {member_no}",
    {"member_no_shown": "40055"}, {"member_no": "40055"}, group="H2",
    note="a mapped field no task has ever read")

for _item in ("W-7701", "W-7702", "W-7704"):
    add("Open the work queue and report the state of work item {item_id}",
        {"state": _work(_item)["state"]}, {"item_id": _item}, group="H2",
        note="the work queue: surveyed only as far as the map goes")


# ============================================================ H3  not a field ==
# Rows, counts and refusals: the answers that are not a labelled value.

# Positional rows, only where the row exists.
_ORDINAL = {1: "first", 2: "second", 3: "third"}
for _member in OPEN:
    for _index, _word in _ORDINAL.items():
        if len(HISTORY[_member]) < _index:
            continue
        date, kind, amount = HISTORY[_member][_index - 1]
        for _phrase, _name, _value in (("amount", f"{_word}_amount", amount),
                                       ("date", f"{_word}_date", date),
                                       ("type", f"{_word}_kind", kind)):
            add(f"Report the {_phrase} of the {_word} posted item for member {{member_no}}",
                {_name: _value}, {"member_no": _member}, group="H3",
                note="selects a row by position")

# Counts, on every table and every member who can reach it.
for _member in OPEN:
    add("Report how many posted items member {member_no} has in total",
        {"item_count": str(len(HISTORY[_member]))}, {"member_no": _member},
        group="H3", note="counts rows")
    add("Report how many standing orders are on file for member {member_no}",
        {"order_count": str(sum(1 for o in ORDERS[_member] if o["status"] == "ACTIVE"))},
        {"member_no": _member}, group="H3",
        note="counts rows — the application counts the active ones")
    add("Report how many audit entries are on file for member {member_no}",
        {"entry_count": str(len(AUDIT[_member]))}, {"member_no": _member},
        group="H3", note="counts rows")

# Refusals: the answer is the message, and which message depends on the argument.
add("Look up member {member_no} and report exactly what the application says",
    {"refusal": "NOT AUTHORISED"}, {"member_no": RESTRICTED}, group="H3",
    note="a restricted record — the only thing this member can be asked")

for _absent in ABSENT:
    add("Look up member {member_no} and report what the screen says about the record",
        {"refusal": "NO MEMBER ON FILE"}, {"member_no": _absent}, group="H3",
        note="a record that is not on file")

for _bad in ("ABC", "40-021"):
    add("Enter {member_no} as the member number and report what the application says",
        {"refusal": "MEMBER NO. MUST BE NUMERIC"}, {"member_no": _bad}, group="H3",
        note="input the application rejects")


# -- nothing here may be something the system was trained on ------------------

for _t in TASKS:
    _run = (_t.goal, tuple(sorted(_t.params.items())))
    assert _run not in _trained_runs, f"task {_t.n} was in the trained set: {_run}"
    if tier(_t) == "H1":
        assert _t.goal in _trained_shapes, f"task {_t.n} is not a recorded shape"
    elif tier(_t) == "H2":
        assert _t.goal not in _trained_shapes, f"task {_t.n} is not a new shape: {_t.goal}"
    # H3 is defined by the kind of answer, not by novelty: a count or a refusal
    # belongs there whether or not something like it was recorded, because what
    # is being measured is whether an answer that is not a field can be produced
    # at all.
    assert _t.params.get("member_no") != RESTRICTED or tier(_t) == "H3", (
        f"task {_t.n} asks the restricted member for something it cannot reach")
